services:
  - type: web
    name: paymind
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn paymind.wsgi:application
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: "paymind.onrender.com"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: paymind-db
          property: connectionString

databases:
  - name: paymind-db
